import { supabaseAdmin } from "./supabase.js";
import { getValidCanvaAccessToken } from "./canvaAuth.js";
import { createDesignFromReel, exportCanvaDesign } from "./canva.js";
import { resolveTemplateId } from "./canvaTemplates.js";
import { persistExportedVideo } from "./storage.js";

interface ReelRow {
  id: string;
  title: string;
  caption_short: string | null;
  category: string | null;
  canva_design_id: string | null;
}

/** Genera (autofill) el diseño en Canva para un reel, usando el template que matchea su categoría. */
export async function generateDesignForReel(
  userId: string,
  reel: ReelRow
): Promise<{ designId: string; editUrl: string; viewUrl: string }> {
  const templateId = resolveTemplateId(reel.category);
  if (!templateId) {
    throw new Error(
      `No hay un template de Canva configurado para la categoría "${reel.category ?? "sin categoría"}" ni un CANVA_BRAND_TEMPLATE_ID por defecto.`
    );
  }

  const accessToken = await getValidCanvaAccessToken(userId);
  const design = await createDesignFromReel(accessToken, templateId, {
    title: { type: "text", text: reel.title },
    hook: { type: "text", text: reel.caption_short ?? reel.title },
  });

  await supabaseAdmin.from("reels").update({ canva_design_id: design.designId, status: "designed" }).eq("id", reel.id);

  return design;
}

/** Exporta el diseño ya generado a MP4/PNG, lo persiste (GCS o disco) y guarda nuestra URL propia. */
export async function exportAndPersistReel(
  userId: string,
  reel: ReelRow,
  format: "mp4" | "png" = "mp4"
): Promise<{ mediaPath: string }> {
  if (!reel.canva_design_id) throw new Error("El reel todavía no tiene diseño en Canva.");

  const accessToken = await getValidCanvaAccessToken(userId);
  const urls = await exportCanvaDesign(accessToken, reel.canva_design_id, format);
  await persistExportedVideo(reel.id, urls[0]);

  const mediaPath = `/api/media/reels/${reel.id}`;
  await supabaseAdmin.from("reels").update({ canva_export_url: mediaPath }).eq("id", reel.id);

  return { mediaPath };
}

/**
 * Flujo completo (diseño + export) para el disparo automático al terminar
 * captions. Es "best-effort": no lanza excepciones hacia el caller (que la
 * dispara fire-and-forget) — solo loguea, para no romper el guardado de
 * captions si Canva falla o no está conectado.
 */
export async function autoGenerateDesignForReel(userId: string, reelId: string): Promise<void> {
  try {
    const { data: reel } = await supabaseAdmin
      .from("reels")
      .select("id, title, caption_short, category, canva_design_id")
      .eq("id", reelId)
      .single();
    if (!reel) return;

    const withDesign = reel.canva_design_id
      ? reel
      : { ...reel, canva_design_id: (await generateDesignForReel(userId, reel)).designId };

    await exportAndPersistReel(userId, withDesign, "mp4");
    console.log(`[canva] diseño auto-generado y exportado para reel ${reelId}`);
  } catch (err) {
    console.error(`[canva] auto-generación falló para reel ${reelId}:`, (err as Error).message);
  }
}
